name: ifoodtv
description: "A new streaming project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  tmdb_api: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_ifood.png
    - assets/logo_wordmark.png
    - assets/background.jpg
    - assets/user.png
    - assets/home_background.png
    - assets/01carrousel.png
    - assets/02carrousel.png
    - assets/03carrousel.png
    - assets/tile_image.png
