name: "IOS - CD"

on:
  push:
    branches: [ prod ]
  workflow_dispatch:
    
jobs:
  build:
    name: IOS BUILD
    runs-on: macos-13
    defaults:
      run:
        working-directory: /
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get

      - name: Instalando certificado e provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPSTORE_CNPMOBILE_APPLEDIST_CERT_BASE64  }}
          P12_PASSWORD: ${{ secrets.APPSTORE_CNPMOBILE_APPLEDIST_CERT_PASSWORD  }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPSTORE_CNPMOBILE_MOBILEPROVISION_BASE64  }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD  }}
        run: |
          chmod a+x ../../.github/workflows/scripts/IOScert_pprofile.sh
          exec ../../.github/workflows/scripts/IOScert_pprofile.sh
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: POD
        run: cd ios && pod install --repo-update && cd ..
      - name: Building IPA
        run: flutter build ipa --export-options-plist ios/exportOptions.plist
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
         name: release-ipa
         path: app_name/build/ios/ipa/release.ipa
         retention-days: 7
      - name: Removendo keychain e provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
          
  upload:
      name: IOS DEPLOY 
      needs: [ build ]
      runs-on: macos-13
      steps:
        - uses: actions/checkout@v4
        - name: App Bundle
          uses: actions/download-artifact@v3
          with:
            name: release-ipa
        - name: 'Upload app to TestFlight'
          uses: apple-actions/upload-testflight-build@v1
          with: 
            app-path: 'release.ipa'
            issuer-id: ${{ secrets.APPSTORE_API_ISSUER_ID }}
            api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
            api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}



      
